name: Deploy

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish to Maven Central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          server_id: sonatype-oss-release
          maven_profiles: release
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_PASSWORD }}
          gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

#      - name: Publish to Maven Central
#        run: mvn -B deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}